version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=bugmanageruser
      - POSTGRES_PASSWORD=bugmanagerpass
      - POSTGRES_DB=bugmanagerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
